# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Run Sonar Scan"
  lane :sonar_scan do
     
    sonar(
      project_key: "PaystackHQ_paystack-sdk-ios",
      project_version: "1.0",
      project_name: "paystack-sdk-ios",
      sources_path: File.expand_path("../Sources/"),
      sonar_organization: "paystackhq",
      sonar_login: ENV["SONAR_TOKEN"],
      sonar_url: "https://sonarcloud.io"
    )  
  end

end
