//
// AuthorizationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum AuthorizationType: String, Codable {
    case _none = "none"
    case pin = "pin"
    case phone = "phone"
    case _3dS = "3DS"
    case otp = "otp"
    case avs = "avs"
}