//
// AVSChargeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AVSChargeRequest: Codable {

    public var trans: String
    public var address: String
    public var city: String
    public var state: String
    public var zipCode: String

    public init(trans: String, address: String, city: String, state: String, zipCode: String) {
        self.trans = trans
        self.address = address
        self.city = city
        self.state = state
        self.zipCode = zipCode
    }

    public enum CodingKeys: String, CodingKey { 
        case trans
        case address
        case city
        case state
        case zipCode = "zip_code"
    }

}
