//
// ChannelOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChannelOptions: Codable {

    public var card: [String]?
    public var bank: [String]?
    public var ussd: [String]?
    public var qr: [String]?

    public init(card: [String]? = nil, bank: [String]? = nil, ussd: [String]? = nil, qr: [String]? = nil) {
        self.card = card
        self.bank = bank
        self.ussd = ussd
        self.qr = qr
    }


}
