//
// Channel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum Channel: String, Codable {
    case card = "card"
    case bank = "bank"
    case ussd = "ussd"
    case qr = "qr"
}