//
// ChargeStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ChargeStatus: String, Codable {
    case success = "success"
    case requery = "requery"
    case ongoing = "ongoing"
    case failed = "failed"
}