//
// ChargeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChargeResponse: Codable {

    public var auth: AuthorizationType?
    public var bank: String?
    public var trans: String?
    public var message: String
    public var otpmessage: String?
    public var redirecturl: String?
    public var reference: String?
    public var countrycode: String?
    public var status: ChargeStatus

    public init(auth: AuthorizationType? = nil, bank: String? = nil, trans: String? = nil, message: String, otpmessage: String? = nil, redirecturl: String? = nil, reference: String? = nil, countrycode: String? = nil, status: ChargeStatus) {
        self.auth = auth
        self.bank = bank
        self.trans = trans
        self.message = message
        self.otpmessage = otpmessage
        self.redirecturl = redirecturl
        self.reference = reference
        self.countrycode = countrycode
        self.status = status
    }


}
