//
// ChargeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChargeRequest: Codable {

    public var clientdata: String?
    public var handle: String
    public var trans: String
    public var last4: String
    public var source: Platform

    public init(clientdata: String? = nil, handle: String, trans: String, last4: String, source: Platform) {
        self.clientdata = clientdata
        self.handle = handle
        self.trans = trans
        self.last4 = last4
        self.source = source
    }


}
