//
// Customer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Customer: Codable {

    public var email: String?
    public var firstName: String?
    public var phone: String?
    public var updatedAt: String?
    public var lastName: String?
    public var _id: Int
    public var createdAt: String?

    public init(email: String? = nil, firstName: String? = nil, phone: String? = nil, updatedAt: String? = nil, lastName: String? = nil, _id: Int, createdAt: String? = nil) {
        self.email = email
        self.firstName = firstName
        self.phone = phone
        self.updatedAt = updatedAt
        self.lastName = lastName
        self._id = _id
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case email
        case firstName = "first_name"
        case phone
        case updatedAt = "updated_at"
        case lastName = "last_name"
        case _id = "id"
        case createdAt = "created_at"
    }

}
