//
// Platform.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum Platform: String, Codable {
    case ios = "ios"
    case android = "android"
    case checkout = "checkout"
}