//
// Transaction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Transaction: Codable {

    public var status: String?
    public var plan: String?
    public var skipPinCheckForCardTypes: [String]?
    public var email: String?
    public var amount: Int?
    public var channels: [Channel]?
    public var transactionStatus: String?
    public var currency: String?
    public var customFilters: String?
    public var reference: String?
    public var merchantKey: String?
    public var _id: Int?
    public var domain: String?
    public var merchantId: Int?
    public var cancelAction: String?
    public var merchantLogo: String?
    public var isRememberMeEnabled: Bool?
    public var accessCode: String?
    public var addedFees: Int?
    public var log: String?
    public var label: String?
    public var channelOptions: ChannelOptions?
    public var originalAmount: Int?
    public var merchantName: String?
    public var customer: Customer?

    public init(status: String? = nil, plan: String? = nil, skipPinCheckForCardTypes: [String]? = nil, email: String? = nil, amount: Int? = nil, channels: [Channel]? = nil, transactionStatus: String? = nil, currency: String? = nil, customFilters: String? = nil, reference: String? = nil, merchantKey: String? = nil, _id: Int? = nil, domain: String? = nil, merchantId: Int? = nil, cancelAction: String? = nil, merchantLogo: String? = nil, isRememberMeEnabled: Bool? = nil, accessCode: String? = nil, addedFees: Int? = nil, log: String? = nil, label: String? = nil, channelOptions: ChannelOptions? = nil, originalAmount: Int? = nil, merchantName: String? = nil, customer: Customer? = nil) {
        self.status = status
        self.plan = plan
        self.skipPinCheckForCardTypes = skipPinCheckForCardTypes
        self.email = email
        self.amount = amount
        self.channels = channels
        self.transactionStatus = transactionStatus
        self.currency = currency
        self.customFilters = customFilters
        self.reference = reference
        self.merchantKey = merchantKey
        self._id = _id
        self.domain = domain
        self.merchantId = merchantId
        self.cancelAction = cancelAction
        self.merchantLogo = merchantLogo
        self.isRememberMeEnabled = isRememberMeEnabled
        self.accessCode = accessCode
        self.addedFees = addedFees
        self.log = log
        self.label = label
        self.channelOptions = channelOptions
        self.originalAmount = originalAmount
        self.merchantName = merchantName
        self.customer = customer
    }

    public enum CodingKeys: String, CodingKey { 
        case status
        case plan
        case skipPinCheckForCardTypes = "skip_pin_check_for_card_types"
        case email
        case amount
        case channels
        case transactionStatus = "transaction_status"
        case currency
        case customFilters = "custom_filters"
        case reference
        case merchantKey = "merchant_key"
        case _id = "id"
        case domain
        case merchantId = "merchant_id"
        case cancelAction = "cancel_action"
        case merchantLogo = "merchant_logo"
        case isRememberMeEnabled = "is_remember_me_enabled"
        case accessCode = "access_code"
        case addedFees = "added_fees"
        case log
        case label
        case channelOptions = "channel_options"
        case originalAmount = "original_amount"
        case merchantName = "merchant_name"
        case customer
    }

}
