//
// TransactionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TransactionResponse: Codable {

    public var status: Bool
    public var message: String
    public var data: Transaction

    public init(status: Bool, message: String, data: Transaction) {
        self.status = status
        self.message = message
        self.data = data
    }


}
