//
// ValidateChargeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ValidateChargeRequest: Codable {

    public var token: String
    public var device: String?
    public var trans: String

    public init(token: String, device: String? = nil, trans: String) {
        self.token = token
        self.device = device
        self.trans = trans
    }


}
