name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-14
    name: Deploy to Cocoapods Trunk

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        xcodebuild clean build test -scheme PaystackSDK-Package -sdk iphonesimulator17.4 -destination "OS=17.4,name=iPhone 15 Pro" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO
        
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.14.2
    
    - name: Run pod lint for Paystack Core
      run: pod lib lint PaystackCore.podspec --allow-warnings

    - name: Get version information
      run: |
        version=$(/usr/libexec/PlistBuddy -c "Print Version" ./Sources/PaystackSDK/Versioning/versions.plist)
        echo "version=${version}" >> $GITHUB_ENV
        body=$(/usr/libexec/PlistBuddy -c "Print Description" ./Sources/PaystackSDK/Versioning/versions.plist)
        echo "body=${body}" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: ${{ env.version }}
        body: ${{ env.body }}

    - name: Install Cocoapods
      run: gem install cocoapods

    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod trunk push PaystackCore.podspec --allow-warnings
        pod trunk push PaystackUI.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        
