name: Primary

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    name: Code quality Checks
    
    steps:
     - uses: actions/checkout@v4
     - name: Danger
       uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
       with:
            args: --failOnErrors --no-publish-check
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  SwiftPackage:
    runs-on: macos-14
    name: Build and Test Swift Package

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3.0'
  
    - name: Setup environment
      run: |
        bundle install

    - name: Build and Run tests
      run: |
        xcodebuild clean build test -scheme PaystackSDK-Package -sdk iphonesimulator17.4 -destination "OS=17.4,name=iPhone 15 Pro" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO
        xcrun llvm-cov show -instr-profile=.build/debug/codecov/default.profdata .build/debug/PaystackSDKPackageTests.xctest/Contents/MacOS/PaystackSDKPackageTests > coverage.report
        brew install sonar-scanner
        bundle exec fastlane sonar_scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  PodLinting:
    runs-on: macos-12
    name: Lint Podspec
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.15.2
    
    - name: Run pod lint for Paystack Core
      run: pod lib lint PaystackCore.podspec --allow-warnings
    

  # TODO: Add sonar here once the project is added
