name: Primary

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    name: Code quality Checks
    
    steps:
     - uses: actions/checkout@v3
     - name: Danger
       uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.16.0
       with:
            args: --failOnErrors --no-publish-check
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build_And_Test_Swift_Package:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  Lint_Pod:
    if: ${{ false }}  # Disabling until we can test if the public cocoapods spec works
    name: Pod Linting
    runs-on: macos-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
               
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.10.1
        
    - name: Pod Linting
      run: |
          rm -rf ~/.cocoapods && pod lib lint --allow-warnings

  # TODO: Add sonar here once the project is added
