name: Primary

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    name: Code quality Checks
    
    steps:
     - uses: actions/checkout@v3
     - name: Danger
       uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
       with:
            args: --failOnErrors --no-publish-check
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  SwiftPackage:
    runs-on: macos-12
    name: Build and Test Swift Package

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
      
  PodLinting:
    runs-on: macos-12
    name: Lint Podspec
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.10.1
    
    - name: Run pod lint for Paystack Core
      run: rm -rf ~/.cocoapods && pod lib lint PaystackCore.podspec --allow-warnings
    

  # TODO: Add sonar here once the project is added
