name: Primary

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
  workflow_dispatch:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    name: Code quality Checks
    
    steps:
     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
     - name: Danger
       uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.22.1
       with:
            args: --failOnErrors --no-publish-check
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  SwiftPackage:
    runs-on: macos-15
    name: Build and Test Swift Package

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: '26.3'

    - name: Setup environment
      run: |
        bundle install

    - name: Build and Run tests
      run: |
        xcodebuild clean build test -scheme PaystackSDK-Package -sdk iphonesimulator26.2 -destination "OS=26.2,name=iPhone 17 Pro" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO
        brew install sonar-scanner
        bundle exec fastlane sonar_scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  PodLinting:
    if: ${{ false }}
    runs-on: macos-15
    name: Lint Podspec

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: setup-cocoapods
      uses: maxim-lobanov/setup-cocoapods@8e97e1e98e6ccf42564fdf5622c8feec74199377 # v1.4.0
      with:
        version: 1.15.2
    
    - name: Run pod lint for Paystack Core
      run: pod lib lint PaystackCore.podspec --allow-warnings
    

  # TODO: Add sonar here once the project is added
