name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        required: true
        description: What version part would you like bump?
        options:
        - patch
        - minor
        - major
      body:
        description: Description for Release

jobs:
  release:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Increment Latest Version
      run: |
        mode=${{ github.event.inputs.release }}
        cd Sources/PaystackSDK
        sh Versioning/update_version.sh $mode ${{ github.event.inputs.body }}

    - name: Open Pull Request
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        commit-message: Updated versions in podspec and plist for release
        title: Updating SDK Version
        body: This is an automated PR to update the versions of the app prior to release. Note that merging this PR will automatically trigger a release. 
        base: main
        branch: release/update-versions
        delete-branch: true
